import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import { Toast } from "@/components/ui/toast";
import Navbar from "@/components/navbar";
import { Toaster } from "@/components/ui/toaster";
import Footer from "@/components/footer";
import AuthProvider from "@/context/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
        <AuthProvider>
      <body className={inter.className} >
        <Navbar/>
        {children}
        <Toaster/>
        {/* <Footer/> */}
        </body>
      </AuthProvider>
    </html>
  );
}
